"""Changed cart.product_id data

Revision ID: c42d566e559c
Revises: e5690901ccb7
Create Date: 2022-06-02 13:09:10.028702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42d566e559c'
down_revision = 'e5690901ccb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
